server:
  port: 8088
spring:
  profiles:
    active: dev
  datasource:
    username:
    password:
    driver-class-name:
    url:
    type:
    druid:
      initial-size:
      min-idle:
      max-active:
      max-wait:
      stat-view-servlet:
        enabled:
        url-pattern:
        login-username:
        login-password:
      filter:
        stat:
          enabled:
          slow-sql-millis:
          log-slow-sql:
        wall:
          enabled:
        config:
          enabled:
  redis:
    # Redis数据库索引（默认为0）
    database:
    # Redis服务器地址
    host:
    # Redis服务器连接端口
    port:
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout:
    lettuce:
      pool:
        # 连接池最大连接数
        max-active:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait:
        # 连接池中的最大空闲连接
        max-idle:
        # 连接池中的最小空闲连接
        min-idle:

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name:
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout:
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout:
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent:
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share:
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style:
  # 是否输出操作日志
  is-log:



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
oss:
  minio:
    url:
    accessKey:
    secretKey:
  aoliyun:
    region:
    accessKeyId:
    accessKeySecret:
    roleArn:
    bucketName:
    endpoint:
file:
  delay:
    time: 10
xxl-job:
  executor:
    # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。
    # 执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    admin-addresses:
    # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
    app-name:
    # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，
    # 该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
    ip:
    # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，
    # 单机部署多个执行器时，注意要配置不同执行器端口；
    port:
    # 执行器通讯TOKEN [选填]：非空时不启用；
    access-token:
    # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
    log-path:
    # 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
    log-retention-days: